# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(unique=True)),
                ('slug', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(db_index=True, max_length=20, unique=True)),
                ('avatar', models.CharField(max_length=24)),
                ('point_lat', models.DecimalField(decimal_places=6, max_digits=8)),
                ('point_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
